backend:
  name: git-gateway
  branch: main # Mettez 'master' si votre branche s'appelle master

media_folder: "vo/images_admin"
public_folder: "vo/images_admin"

collections:
  - name: "vehicules"
    label: "Ajouter un Véhicule"
    folder: "vo_data_auto" # Le dossier où vos annonces seront créées
    create: true
    extension: "json" # On enregistre en format lisible par le site
    slug: "{{id}}"
    fields:
      - {label: "Identifiant Unique (ex: clio-2024)", name: "id", widget: "string"}
      - {label: "Nom du véhicule", name: "title", widget: "string"}
      - {label: "Prix (€)", name: "price", widget: "number"}
      - {label: "Kilométrage", name: "km", widget: "number"}
      - {label: "Année", name: "year", widget: "number"}
      - {label: "Carburant", name: "fuel", widget: "select", options: ["Diesel", "Essence", "Hybride", "Électrique", "Éthanol"]}
      - {label: "Résumé (Court)", name: "summary", widget: "text"}
      - {label: "Photo Principale", name: "mainImageUrl", widget: "image"}
      - {label: "Badge (ex: Occasion, Vendu)", name: "badge", widget: "string", required: false}
